separator=false
markup=pango

[terminal]
full_text=  
color=#807dfe
command=i3-msg -q exec ghostty

[browser]
full_text= 
color=#ff7f81
command=i3-msg -q exec brave

[files]
full_text=  
color=#7f3fbf
command=i3-msg -q exec thunar ~/

[mail]
full_text=  
color=#dbcb75
command=i3-msg -q exec betterbird

[simple-2]
full_text=: :
color=#e4db73

[disk]
label= 
instance=/
command=~/.config/i3/scripts/disk
interval=30

[memory]
label= 
command=~/.config/i3/scripts/memory
interval=2

[cpu_usage]
label= 
command=~/.config/i3/scripts/cpu_usage
#min_width=CPU: 100.00%
interval=2

[CPU-temperature]
label=
command=~/.config/i3/scripts/temperature
interval=5
SENSOR_CHIP="coretemp-isa-0000"

[GPU-temp]
label=
command=~/.config/i3/scripts/temperature
interval=5
SENSOR_CHIP="amdgpu-pci-0300"

[simple-2]
full_text=: :
color=#e4db73

[pavucontrol]
full_text= 
command=pavucontrol

[volume-pulseaudio]
command=~/.config/i3/scripts/volume
instance=Master
interval=1

# display keyboard layout name
# for keyboard layouts switcher
# see i3 config file
# this needs xkblayout-state installed from the AUR:
# https://aur.archlinux.org/packages/xkblayout-state-git
[keyboard-layout]
command=~/.config/i3/scripts/keyboard-layout
interval=2

[time]
command=date '+%a %d %b %H:%M:%S'
interval=1

[shutdown_menu]
full_text= 
command=~/.config/i3/scripts/powermenu

[simple-2]
full_text=: :
color=#e4db73
